#!/usr/bin/env python3
"""Example of using System class for FreyjaCLI utilities."""

from freyja import FreyjaCLI
from freyja.cli.system import System

if __name__ == '__main__':
  cli = FreyjaCLI(
    System,
    title="System Utilities FreyjaCLI - Built-in Commands",
    completion=True,
  )

  result = cli.run()
  exit(result if isinstance(result, int) else 0)
